/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WeekDiary = IDL.Record({
  'goalAchieved' : IDL.Bool,
  'week' : IDL.Nat,
  'notes' : IDL.Text,
  'challenges' : IDL.Text,
  'strategies' : IDL.Text,
});
export const Day = IDL.Variant({
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'monday' : IDL.Null,
});
export const TrainingSession = IDL.Record({
  'day' : Day,
  'week' : IDL.Nat,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAllDiaries' : IDL.Func([], [IDL.Vec(WeekDiary)], ['query']),
  'getTotalProgress' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrainingSession' : IDL.Func([IDL.Nat, Day], [TrainingSession], ['query']),
  'getWeekDiary' : IDL.Func([IDL.Nat], [WeekDiary], ['query']),
  'saveTrainingSession' : IDL.Func([TrainingSession], [], []),
  'saveWeekDiary' : IDL.Func([WeekDiary], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WeekDiary = IDL.Record({
    'goalAchieved' : IDL.Bool,
    'week' : IDL.Nat,
    'notes' : IDL.Text,
    'challenges' : IDL.Text,
    'strategies' : IDL.Text,
  });
  const Day = IDL.Variant({
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const TrainingSession = IDL.Record({
    'day' : Day,
    'week' : IDL.Nat,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    'getAllDiaries' : IDL.Func([], [IDL.Vec(WeekDiary)], ['query']),
    'getTotalProgress' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrainingSession' : IDL.Func(
        [IDL.Nat, Day],
        [TrainingSession],
        ['query'],
      ),
    'getWeekDiary' : IDL.Func([IDL.Nat], [WeekDiary], ['query']),
    'saveTrainingSession' : IDL.Func([TrainingSession], [], []),
    'saveWeekDiary' : IDL.Func([WeekDiary], [], []),
  });
};

export const init = ({ IDL }) => { return []; };