/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Day = { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'monday' : null };
export interface TrainingSession {
  'day' : Day,
  'week' : bigint,
  'completed' : boolean,
}
export interface WeekDiary {
  'goalAchieved' : boolean,
  'week' : bigint,
  'notes' : string,
  'challenges' : string,
  'strategies' : string,
}
export interface _SERVICE {
  'getAllDiaries' : ActorMethod<[], Array<WeekDiary>>,
  'getTotalProgress' : ActorMethod<[], bigint>,
  'getTrainingSession' : ActorMethod<[bigint, Day], TrainingSession>,
  'getWeekDiary' : ActorMethod<[bigint], WeekDiary>,
  'saveTrainingSession' : ActorMethod<[TrainingSession], undefined>,
  'saveWeekDiary' : ActorMethod<[WeekDiary], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];