/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrainingSession {
    day: Day;
    week: bigint;
    completed: boolean;
}
export interface WeekDiary {
    goalAchieved: boolean;
    week: bigint;
    notes: string;
    challenges: string;
    strategies: string;
}
export enum Day {
    wednesday = "wednesday",
    saturday = "saturday",
    monday = "monday"
}
export interface backendInterface {
    getAllDiaries(): Promise<Array<WeekDiary>>;
    getTotalProgress(): Promise<bigint>;
    getTrainingSession(week: bigint, day: Day): Promise<TrainingSession>;
    getWeekDiary(week: bigint): Promise<WeekDiary>;
    saveTrainingSession(session: TrainingSession): Promise<void>;
    saveWeekDiary(entry: WeekDiary): Promise<void>;
}
import type { Day as _Day, TrainingSession as _TrainingSession } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllDiaries(): Promise<Array<WeekDiary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiaries();
            return result;
        }
    }
    async getTotalProgress(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalProgress();
            return result;
        }
    }
    async getTrainingSession(arg0: bigint, arg1: Day): Promise<TrainingSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingSession(arg0, to_candid_Day_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TrainingSession_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingSession(arg0, to_candid_Day_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TrainingSession_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeekDiary(arg0: bigint): Promise<WeekDiary> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeekDiary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeekDiary(arg0);
            return result;
        }
    }
    async saveTrainingSession(arg0: TrainingSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTrainingSession(to_candid_TrainingSession_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTrainingSession(to_candid_TrainingSession_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveWeekDiary(arg0: WeekDiary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWeekDiary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWeekDiary(arg0);
            return result;
        }
    }
}
function from_candid_Day_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Day): Day {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingSession_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingSession): TrainingSession {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _Day;
    week: bigint;
    completed: boolean;
}): {
    day: Day;
    week: bigint;
    completed: boolean;
} {
    return {
        day: from_candid_Day_n5(_uploadFile, _downloadFile, value.day),
        week: value.week,
        completed: value.completed
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wednesday: null;
} | {
    saturday: null;
} | {
    monday: null;
}): Day {
    return "wednesday" in value ? Day.wednesday : "saturday" in value ? Day.saturday : "monday" in value ? Day.monday : value;
}
function to_candid_Day_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): _Day {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingSession_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingSession): _TrainingSession {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: Day;
    week: bigint;
    completed: boolean;
}): {
    day: _Day;
    week: bigint;
    completed: boolean;
} {
    return {
        day: to_candid_Day_n1(_uploadFile, _downloadFile, value.day),
        week: value.week,
        completed: value.completed
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): {
    wednesday: null;
} | {
    saturday: null;
} | {
    monday: null;
} {
    return value == Day.wednesday ? {
        wednesday: null
    } : value == Day.saturday ? {
        saturday: null
    } : value == Day.monday ? {
        monday: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
